config/routes.rb
Rails.application.routes.draw do
  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Main routes
  root "catalog#index"
  devise_for :customers, :controllers => { registrations: 'customers/registrations' }

  resources :catalog do
    collection do
      get :show_years
      get :show_models
      get :show_categories
      get :show_types
      get :show_products
    end
  end
  get "search", to: "catalog#search", as: "search_catalog"

  get "product/:id", to: "product#show", as: "product"

  get "cart", to: "cart#index", as: "cart"
  post "cart/add/:id", to: "cart#add_to_cart", as: "add_to_cart"
  delete "cart/delete/:id", to: "cart#delete_from_cart", as: "delete_from_cart"
  post "cart/update/:id", to: "cart#update_cart_quantity", as: "update_cart_quantity"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/totals", to: "checkout#totals", as: "checkout_totals"
  post "checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "checkout/success", to: "checkout#success", as: "checkout_success"

  get "orders", to: "order#index", as: "orders"
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :initialize_session
  before_action :load_cart

  def index
    @customer = current_customer || Customer.new
  end

  def totals
    @province = Province.find(params[:province] || 1)
    @subtotal = BigDecimal(0.00)
    @cart.each do |product_id, quantity|
      @subtotal += Product.find(product_id).price * quantity
    end

    @pst_total = @province.pst_rate? ? BigDecimal(@subtotal) * @province.pst_rate : BigDecimal(0.00)
    @gst_total = @province.gst_rate? ? BigDecimal(@subtotal) * @province.gst_rate : BigDecimal(0.00)
    @hst_total = @province.hst_rate? ? BigDecimal(@subtotal) * @province.hst_rate : BigDecimal(0.00)
    @total = @subtotal + @pst_total + @gst_total + @hst_total
  end

  def place_order
    validated = current_customer ? handle_current_customer : handle_new_customer
    render :index, status: :unprocessable_entity and return unless validated

    create_order_from_cart(@customer)
    redirect_to checkout_success_path
  end

  private

  def initialize_session
    session[:cart] ||= {}
  end

  def load_cart
    @cart = session[:cart]
  end

  def customer_params
    params.require(:customer).permit(:full_name, :email, :phone_number, :street_address1,
                                     :street_address2, :city, :postal_code, :postal_code,
                                     :province_id)
  end

  def handle_current_customer
    @customer = current_customer
    @customer.update(customer_params) # true if success, false otherwise
  end

  def handle_new_customer
    @customer = Customer.new(customer_params)
    @customer.skip_password_validation = true
    @customer.save
  end

  def create_order_from_cart(cust)
    create_order_items(create_order(cust), session[:cart])
    session[:cart] = {}
  end

  def create_order(cust)
    Order.create!(customer: cust, status: Order.statuses[:pending],
                  gst_rate: cust.province.gst_rate,
                  pst_rate: cust.province.pst_rate,
                  hst_rate: cust.province.hst_rate)
  end

  def create_order_items(order, cart)
    cart.each do |product_id, quantity|
      product = Product.find(product_id)
      OrderItem.create(order_id: order.id, product:, price: product.price, quantity:)
    end
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def rate_to_percentage(rate)
    number_to_percentage(rate * 100, precision: 10, strip_insignificant_zeros: true)
  end
end

app/views/checkout/index.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl mb-2">Checkout</h1>
  <div class="flex flex-row gap-8">
    <div class="flex-1">
      <%= form_with model: @customer, url: checkout_place_order_path, method: :post do |customer_form| %>
        <div class="mb-2">
          <%= customer_form.label :full_name, "Full Name", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :full_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-2">
          <%= customer_form.label :email, "Email", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :email, disabled: current_customer, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" + (current_customer ? " cursor-not-allowed" : "") %>
        </div>
        <div class="mb-2">
          <%= customer_form.label :phone_number, "Phone Number", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :phone_number, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-2">
          <%= customer_form.label :street_address1, "Street Address", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :street_address1, class: "mb-2 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
          <%= customer_form.text_field :street_address2, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-2">
          <%= customer_form.label :city, "City", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :city, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-2">
          <%= customer_form.label :postal_code, "Postal Code", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.text_field :postal_code, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-5" data-controller="select-turbo" data-select-turbo-url-value="/checkout/totals" data-select-turbo-url-param-value="province" data-select-turbo-frame-tag-value="totals">
          <%= customer_form.label :province_id, "Province", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= customer_form.collection_select :province_id, Province.order(:name), :id, :name, {}, { data: { "select-turbo-target": "select" }, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
        </div>
        <%= customer_form.submit "Place Order", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      <% end %>
    </div>
    <div class="flex-1">
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg mb-4">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Product
            </th>
            <th scope="col" class="px-6 py-3">
              Price
            </th>
            <th scope="col" class="px-6 py-3">
              Quantity
            </th>
            <th scope="col" class="px-6 py-3">
              Total
            </th>
          </tr>
          </thead>
          <tbody>
          <% @cart.each do |product_id, quantity| %>
            <% product = Product.find(product_id) %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
              <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white flex flex-row items-center gap-1">
                <% if product.image.attached? %>
                  <img class="border-[1px]" src="<%= url_for(product.image) %>" width="64" height="64" />
                <% end %>
                <div class="flex-1"><%= product.product_brand.name %> <%= product.product_number %></div>
              </td>
              <td class="px-6 py-4">
                <%= number_to_currency(product.price) %>
              </td>
              <td class="px-6 py-4">
                <%= quantity %>
              </td>
              <td class="px-6 py-4">
                $<%= product.price * quantity %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <%= turbo_frame_tag "totals", src: "#{checkout_totals_path}?province=#{Province.order(:name).first.id}" %>
    </div>
  </div>
</div>

app/views/checkout/success.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl mb-2">Order placed successfully!</h1>
  <div>
    <p>Return to our <%= link_to "Catalog?", catalog_index_path, class: "text-blue-700 hover:underline" %></p>
  </div>
</div>

app/views/checkout/totals.html.erb
<%= turbo_frame_tag "totals" do %>
  <p>Subtotal: $<%= @subtotal %></p>
  <% if @gst_total > 0 %>
    <p>GST (<%= rate_to_percentage(@province.gst_rate) %>): <%= number_to_currency(@gst_total) %></p>
  <% end %>
  <% if @pst_total > 0 %>
    <p>PST (<%= rate_to_percentage(@province.pst_rate) %>): <%= number_to_currency(@pst_total) %></p>
  <% end %>
  <% if @hst_total > 0 %>
    <p>HST (<%= rate_to_percentage(@province.hst_rate) %>): <%= number_to_currency(@hst_total) %></p>
  <% end %>
  <p>Order Total: <span class="font-bold"><%= number_to_currency(@total) %></span></p>
<% end %>