config/routes.rb
Rails.application.routes.draw do
  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Main routes
  root "catalog#index"
  devise_for :customers, :controllers => { registrations: 'customers/registrations' }

  resources :catalog do
    collection do
      get :show_years
      get :show_models
      get :show_categories
      get :show_types
      get :show_products
    end
  end
  get "search", to: "catalog#search", as: "search_catalog"

  get "product/:id", to: "product#show", as: "product"

  get "cart", to: "cart#index", as: "cart"
  post "cart/add/:id", to: "cart#add_to_cart", as: "add_to_cart"
  delete "cart/delete/:id", to: "cart#delete_from_cart", as: "delete_from_cart"
  post "cart/update/:id", to: "cart#update_cart_quantity", as: "update_cart_quantity"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/totals", to: "checkout#totals", as: "checkout_totals"
  post "checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "checkout/success", to: "checkout#success", as: "checkout_success"

  get "orders", to: "order#index", as: "orders"
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
    @makes = VehicleMake.all.order(:name)
  end

  def show_years
    @make = VehicleMake.where(name: params[:make]).first
    @years = @make.vehicle_years.all.order(:year).reverse
  end

  def show_models
    @make = VehicleMake.where(name: params[:make]).first
    @year = VehicleYear.where(year: params[:year]).first
    @models = Vehicle.where(vehicle_make: @make, vehicle_year: @year).includes(:vehicle_model)
  end

  def show_categories
    @vehicle = Vehicle.find(params[:vehicle_id])
    fitments = ProductFitment.where(vehicle: @vehicle).includes(:product)
    @cats = []
    fitments.each do |fitment|
      @cats.append(fitment.product.product_type.product_category)
    end
    @cats = @cats.uniq
  end

  def show_types
    @vehicle = Vehicle.find(params[:vehicle_id])
    @category = ProductCategory.find(params[:product_category_id])
    fitments = ProductFitment.where(vehicle: @vehicle).includes(:product)
    @types = []
    fitments.each do |fitment|
      type = fitment.product.product_type
      @types.append(type) if type.product_category == @category
    end
    @types = @types.uniq
  end

  def show_products
    @vehicle = Vehicle.find(params[:vehicle_id])
    @type = ProductType.find(params[:product_type_id])
    fitments = ProductFitment.where(vehicle: @vehicle).includes(:product)
    @products = []
    fitments.each do |fitment|
      product = fitment.product
      @products.append(product) if product.product_type == @type
    end
    @products = @products.sort_by(&:price)
  end

  def search
    if params[:category].blank?
      @types = ProductType.all
    else
      @category = ProductCategory.find(params[:category])
      @types = ProductType.where(product_category: @category)
    end
    @filtered_types = @types.where("LOWER(name) LIKE ? OR LOWER(description) LIKE ?",
                                   "%#{params[:query].downcase}%", "%#{params[:query].downcase}%")
    @products = Product.where(product_type: @filtered_types)
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/_accordion_item.html.erb
<div id="accordion-<%= dom_id(item) %>" data-controller="toggle">
  <h2 id="accordion-toggle-<%= dom_id(item) %>">
    <button type="button" class="flex items-center font-medium gap-1" data-action="toggle#toggle">
      <svg class="w-6 h-6" data-toggle-target="item" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 7.757v8.486M7.757 12h8.486M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
      </svg>
      <svg class="hidden w-6 h-6" data-toggle-target="item" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 9-6 6m0-6 6 6m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
      </svg>
      <span><%= item_name %></span>
    </button>
  </h2>
  <div id="accordion-body-<%= dom_id(item) %>" class="hidden -mt-1" data-toggle-target="item">
    <%= yield %>
  </div>
</div>

app/views/catalog/_product.html.erb
<div class="flex flex-col flex-1 space-y-1"> <!-- Product Details -->
  <div>
    <p>
      <%= product.product_brand.name %> <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline"><%= product.product_number %></a>
    </p>
  </div>
  <div>
    <a href="<%= product_path(product) %>" data-turbo-frame="_top" class="px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Info</a>
  </div>
  <div>
    <p><%= product.name %></p>
  </div>
</div>
<div class="self-center">
  <% if product.image.attached? %>
    <img class="border-[1px]" src="<%= url_for(product.image) %>" width="64" height="64" />
  <% end %>
</div> <!-- Image -->
<form class="flex space-x-4" action="<%= add_to_cart_path(product) %>" method="post">
  <div class="font-bold self-center"><%= number_to_currency(product.price) %></div>
  <div class="relative formkit-field self-center">
    <div class="relative flex items-center max-w-[8rem]" data-controller="quantity">
      <button type="button" data-action="quantity#decrement"  class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-s-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
        <svg class="w-3 h-3 text-gray-900 dark:text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 2">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h16"/>
        </svg>
      </button>
      <input type="text" name="quantity" data-quantity-target="counter" min="1" max="99" class="bg-gray-50 border-x-0 border-gray-300 h-11 text-center text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full py-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" value="1" />
      <button type="button" data-action="quantity#increment" class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
        <svg class="w-3 h-3 text-gray-900 dark:text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
        </svg>
      </button>
    </div>
  </div>
  <button type="submit" data-turbo-frame="cart" class="self-center focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 h-11 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Add to Cart</button>
</form> <!-- Price/Buy -->

app/views/catalog/index.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl mb-2">Catalog</h1>
  <div class="flex flex-row gap-8">
    <div class="flex-1"> <!-- Catalog -->
      <% @makes.each do |make| %> <!-- Make -->
        <%= render layout: "accordion_item", locals: { item: make, item_name: make.name } do %>
          <%= turbo_frame_tag make, src: show_years_catalog_index_path(params: { make: make.name }), loading: "lazy" %>
        <% end %>
      <% end %>
    </div>
    <div class="flex-1"> <!-- Cart -->
      <%= turbo_frame_tag "cart", src: cart_path %>
    </div>
  </div>
</div>

app/views/catalog/search.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">
    Search <span class="text-lg font-normal text-gray-500 lg:text-xl">for "<%= params[:query] %>"
    <% if @category %>
        in <%= @category.name %>
      <% end %>
      </span>
  </h1>
  <div class="flex flex-row gap-8">
    <div class="flex-1"> <!-- Search -->
      <ul class="border border-gray-200 rounded-lg mt-1">
        <% @products.each do |product| %>
          <li class="odd:bg-gray-100 even:bg-gray-200 border-b flex flex-row p-2 space-x-4">
            <%= render partial: "product", locals: { product: product } %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="w-1/2"> <!-- Cart -->
      <%= turbo_frame_tag "cart", src: cart_path %>
    </div>
  </div>
</div>

app/views/catalog/show_categories.html.erb
<%= turbo_frame_tag @vehicle do %>
  <div class="flex flex-row">
    <div class="w-6 flex justify-center"> <!-- Line -->
      <div class="w-[2px] h-full bg-black"></div>
    </div>

    <div class="ml-2 mt-1">
      <div id="accordion-categories" data-accordion="open" data-active-classes="bg-white text-gray-900" data-inactive-classes="text-gray-900">
        <% @cats.each do |cat| %>
          <%= render layout: "accordion_item", locals: { item: cat, item_name: cat.name } do %>
            <%= turbo_frame_tag cat, src: show_types_catalog_index_path(params: { vehicle_id: @vehicle, product_category_id: cat }), loading: "lazy" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/show_models.html.erb
<%= turbo_frame_tag @year do %>
  <div class="flex flex-row">
    <div class="w-6 flex justify-center"> <!-- Line -->
      <div class="w-[2px] h-full bg-black"></div>
    </div>

    <div class="ml-2 mt-1">
      <div id="accordion-models" data-accordion="open" data-active-classes="bg-white text-gray-900" data-inactive-classes="text-gray-900">
        <% @models.each do |vehicle| %>
          <%= render layout: "accordion_item", locals: { item: vehicle, item_name: vehicle.vehicle_model.name } do %>
            <%= turbo_frame_tag vehicle, src: show_categories_catalog_index_path(params: { vehicle_id: vehicle }), loading: "lazy" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/show_products.html.erb
<%= turbo_frame_tag @type do %>
  <ul class="border border-gray-200 rounded-lg mt-1">
    <% @products.each do |product| %>
      <li class="odd:bg-gray-100 even:bg-gray-200 border-b flex flex-row p-2 space-x-4">
        <%= render partial: "product", locals: { product: product } %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/catalog/show_types.html.erb
<%= turbo_frame_tag @category do %>
  <div class="flex flex-row">
    <div class="w-6 flex justify-center"> <!-- Line -->
      <div class="w-[2px] h-full bg-black"></div>
    </div>

    <div class="ml-2 mt-1">
      <div id="accordion-types" data-accordion="open" data-active-classes="bg-white text-gray-900" data-inactive-classes="text-gray-900">
        <% @types.each do |type| %>
          <%= render layout: "accordion_item", locals: { item: type, item_name: type.name } do %>
            <%= turbo_frame_tag type, src: show_products_catalog_index_path(params: { vehicle_id: @vehicle, product_type_id: type }), loading: "lazy" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/show_years.html.erb
<%= turbo_frame_tag @make do %>
  <div class="flex flex-row">
    <div class="w-6 flex justify-center"> <!-- Line -->
      <div class="w-[2px] h-full bg-black"></div>
    </div>

    <div class="ml-2 mt-1">
      <div id="accordion-years" data-accordion="open" data-active-classes="bg-white text-gray-900" data-inactive-classes="text-gray-900">
        <% @years.each do |year| %>
          <%= render layout: "accordion_item", locals: { item: year, item_name: year.year } do %>
            <%= turbo_frame_tag year, src: show_models_catalog_index_path(params: { make: @make.name, year: year.year }), loading: "lazy" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>