config/routes.rb
Rails.application.routes.draw do
  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Main routes
  root "catalog#index"
  devise_for :customers, :controllers => { registrations: 'customers/registrations' }

  resources :catalog do
    collection do
      get :show_years
      get :show_models
      get :show_categories
      get :show_types
      get :show_products
    end
  end
  get "search", to: "catalog#search", as: "search_catalog"

  get "product/:id", to: "product#show", as: "product"

  get "cart", to: "cart#index", as: "cart"
  post "cart/add/:id", to: "cart#add_to_cart", as: "add_to_cart"
  delete "cart/delete/:id", to: "cart#delete_from_cart", as: "delete_from_cart"
  post "cart/update/:id", to: "cart#update_cart_quantity", as: "update_cart_quantity"

  get "checkout", to: "checkout#index", as: "checkout"
  get "checkout/totals", to: "checkout#totals", as: "checkout_totals"
  post "checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "checkout/success", to: "checkout#success", as: "checkout_success"

  get "orders", to: "order#index", as: "orders"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "email"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :skip_password_validation

  belongs_to :province

  validates :full_name, presence: true
  validates :email,
            presence:   true,
            uniqueness: true,
            format:     { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, presence: true
  validates :street_address1, presence: true
  validates :street_address2,
            presence:    true,
            allow_blank: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :province, presence: true

  protected

  def password_required?
    return false if skip_password_validation

    super
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  enum :status, %i[pending paid shipped delivered]

  validates :customer, presence: true
  validates :status, presence: true
  validates :gst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
  validates :pst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
  validates :hst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }

  def subtotal
    subtotal = BigDecimal(0.0)
    order_items.each do |order_item|
      subtotal += order_item.product.price * order_item.quantity
    end
    subtotal
  end

  def pst_total
    subtotal * pst_rate
  end

  def gst_total
    subtotal * gst_rate
  end

  def hst_total
    subtotal * hst_rate
  end

  def grand_total
    sub = subtotal
    pst_total = pst_rate? ? BigDecimal(sub) * pst_rate : BigDecimal(0.00)
    gst_total = gst_rate? ? BigDecimal(sub) * gst_rate : BigDecimal(0.00)
    hst_total = hst_rate? ? BigDecimal(sub) * hst_rate : BigDecimal(0.00)
    sub + pst_total + gst_total + hst_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order, presence: true
  validates :product, presence: true
  validates :price,
            presence:     true,
            numericality: { greater_than_or_equal_to: 0 }
  validates :quantity,
            presence:     true,
            numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_brand
  belongs_to :product_type
  has_one_attached :image

  validates :product_brand, presence: true
  validates :product_type, presence: true
  validates :product_number, presence: true
  validates :name, presence: true
  validates :description,
            presence:    true,
            allow_blank: true
  validates :price,
            presence:     true,
            numericality: { greater_than_or_equal_to: 0 }
  validates :extended_data, presence: true

  def self.ransackable_associations(_auth_object = nil)
    ["product_brand", "product_category"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "name", "description", "price", "product_brand_id", "product_type_id",
     "product_number", "updated_at"]
  end
end

app/models/product_brand.rb
class ProductBrand < ApplicationRecord
  validates :name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "name", "updated_at"]
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  validates :name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "name", "updated_at"]
  end
end

app/models/product_fitment.rb
class ProductFitment < ApplicationRecord
  belongs_to :product
  belongs_to :vehicle

  validates :product, presence: true
  validates :vehicle, presence: true

  def self.ransackable_associations(_auth_object = nil)
    ["product", "vehicle"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "product_id", "vehicle_id", "updated_at"]
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product_category

  validates :name, presence: true

  def self.ransackable_associations(_auth_object = nil)
    ["product_category"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "product_category_id", "name", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  validates :gst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0 }
  validates :pst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0 }
  validates :hst_rate,
            allow_blank:  true,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0 }

  def self.ransackable_attributes(_auth_object = nil)
    ["name", "gst_rate", "pst_rate", "hst_rate", "created_at", "updated_at"]
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_year
  belongs_to :vehicle_make
  belongs_to :vehicle_model

  validates :vehicle_year, presence: true
  validates :vehicle_make, presence: true
  validates :vehicle_model, presence: true

  def self.ransackable_associations(_auth_object = nil)
    ["vehicle_year", "vehicle_make", "vehicle_model"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["vehicle_year_id", "vehicle_make_id", "vehicle_model_id", "created_at", "updated_at"]
  end
end

app/models/vehicle_make.rb
class VehicleMake < ApplicationRecord
  has_many :vehicles, dependent: :destroy
  has_many :vehicle_years, through: :vehicles

  validates :name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "name", "updated_at"]
  end
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  has_many :vehicles, dependent: :destroy

  validates :name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "name", "updated_at"]
  end
end

app/models/vehicle_year.rb
class VehicleYear < ApplicationRecord
  has_many :vehicles, dependent: :destroy

  validates :year,
            presence:     true,
            numericality: { only_integer: true },
            length:       { is: 4 } # a little bit of typo safety

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "year", "updated_at"]
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def rate_to_percentage(rate)
    number_to_percentage(rate * 100, precision: 10, strip_insignificant_zeros: true)
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/_navbar.html.erb
<nav class="border-gray-200 border-b">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4 space-x-8">
    <a href="/" class="flex items-center space-x-3">
      <span class="self-center text-2xl font-semibold whitespace-nowrap">RockMoto</span>
    </a>
    <div class="flex flex-1">
      <div class="w-full">
        <%= form_with url: search_catalog_path, method: :get do |search_form| %>
          <div class="flex">
            <%= search_form.collection_select :category, ProductCategory.order(:name), :id, :name, { :prompt => "All" }, { class: "bg-gray-100 border border-gray-300 text-gray-900 text-sm rounded-s-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5" } %>
            <div class="relative w-full">
              <%= search_form.search_field :query, placeholder: "Search...", required: true, class: "block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-lg border-s-gray-50 border border-gray-300 focus:ring-blue-500 focus:border-blue-500" %>
              <button type="submit" data-turbo-frame="_top" class="absolute top-0 end-0 p-2.5 text-sm font-medium h-full text-white bg-blue-700 rounded-e-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
                <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="items-center justify-between flex w-auto" id="navbar-search">
      <ul class="flex font-medium space-x-8 flex-row">
        <li>
          <a href="/" class="block hover:text-blue-700">Home</a>
        </li>
        <% if current_customer %>
          <li>
            <%= link_to "My Orders", orders_path, class: "block hover:text-blue-700" %>
          </li>
          <li>
            <%= button_to "Sign out", destroy_customer_session_path, method: :delete, class: "block hover:text-blue-700" %>
          </li>
          <% else %>
          <li>
            <%= link_to "Sign up", new_customer_registration_path, class: "block hover:text-blue-700" %>
          </li>
          <li>
            <%= link_to "Log in", customer_session_path, class: "block hover:text-blue-700" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rockmoto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>